options:
  logging: CLOUD_LOGGING_ONLY # Ensures logs are sent only to Cloud Logging

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy image-resizer \
          --gen2 \
          --runtime=nodejs18 \
          --region=us-central1 \
          --trigger-event=google.storage.object.finalize \
          --trigger-resource=upload-bucket-experiment \
          --entry-point=image-resizer \
          --set-env-vars=PROCESSED_BUCKET=processed-bucket-experiment \
          --timeout=540s \
          --service-account=711052490590-compute@developer.gserviceaccount.com \
          --project=bamboo-medium-448219-i3
timeout: 1200s

