service: gcp-image-processing

provider:
  name: google
  runtime: nodejs18
  region: us-central1
  project: bamboo-medium-448219-i3
  credentials: ~/gcp-keyfile.json

functions:
  imageResizer:
    handler: handler.imageResizer
    events:
      - eventType: google.storage.object.finalize
        resource: projects/_/buckets/upload-bucket-experiment
    environment:
      PROCESSED_BUCKET: processed-bucket-experiment

resources:
  Resources:
    UploadBucket:
      Type: google::storage::v1::Bucket
      Properties:
        name: upload-bucket-experiment

    ProcessedBucket:
      Type: google::storage::v1::Bucket
      Properties:
        name: processed-bucket-experiment

